version: 2.1

orbs:
  win: circleci/windows@2.2.0

Workflows:
  Windows-hello:
  
  jobs:
    build:
      executor: win/default
      steps:
        - checkout
        - run: Write-Host 'Hello, Windows'
