version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      #- run: ls -lah
      - run:
          command: ping localhost
          shell: cmd.exe
      - run:
          command: echo 'This is powershell'
          shell: powershell.exe
